# Generated by Django 6.0.2 on 2026-02-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('stackoverflow', 'Stack Overflow'), ('medium', 'Medium'), ('blog', 'Blog')], max_length=20),
        ),
    ]
