# Generated by Django 6.0.2 on 2026-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the upcoming project', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly slug for the project', unique=True)),
                ('description', models.TextField(help_text='Brief description of the project')),
                ('short_description', models.CharField(help_text='Short description for cards/tiles', max_length=200)),
                ('expected_launch', models.DateField(blank=True, help_text='Expected launch date', null=True)),
                ('image', models.ImageField(blank=True, help_text='Preview or concept image', null=True, upload_to='upcoming_projects/')),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list of technologies to be used', max_length=500)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_development', 'In Development'), ('testing', 'Testing'), ('launching_soon', 'Launching Soon')], default='planned', help_text='Current status of the project', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured section on homepage')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upcoming Project',
                'verbose_name_plural': 'Upcoming Projects',
                'ordering': ['order', 'expected_launch', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active', 'expected_launch'], name='portfolio_u_status_6b0d5c_idx'), models.Index(fields=['featured', 'is_active'], name='portfolio_u_feature_49e021_idx')],
            },
        ),
    ]
