# Generated by Django 6.0.2 on 2026-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_upcomingproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, storage='cloudinary_storage.storage.RawMediaCloudinaryStorage', upload_to='resume/'),
        ),
    ]
