# Generated by Django 6.0.2 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_siteinfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]