# Generated by Django 6.0.2 on 2026-06-06 11:11

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_siteinfo_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resume/'),
        ),
    ]
